#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PleaseWorkV1.Resource", IsApplication=true)]

namespace PleaseWorkV1
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int border = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int buttonborder = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int gradient = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int qublogo = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int ChildrenIDTV = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int EndTV = 2131034114;
			
			// aapt resource value: 0x7f050019
			public const int InternetConnectionTV = 2131034137;
			
			// aapt resource value: 0x7f050007
			public const int Intro = 2131034119;
			
			// aapt resource value: 0x7f05001f
			public const int ListViewExpanded = 2131034143;
			
			// aapt resource value: 0x7f050004
			public const int LocationTV = 2131034116;
			
			// aapt resource value: 0x7f050018
			public const int Logout = 2131034136;
			
			// aapt resource value: 0x7f05001d
			public const int NotesTVN = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int ParentTVID = 2131034142;
			
			// aapt resource value: 0x7f05001a
			public const int StartDateTV = 2131034138;
			
			// aapt resource value: 0x7f050001
			public const int StartTV = 2131034113;
			
			// aapt resource value: 0x7f05001b
			public const int StartTimeTV = 2131034139;
			
			// aapt resource value: 0x7f050003
			public const int SubjectTV = 2131034115;
			
			// aapt resource value: 0x7f05001c
			public const int SubjectTVN = 2131034140;
			
			// aapt resource value: 0x7f050005
			public const int SupportHeading = 2131034117;
			
			// aapt resource value: 0x7f050016
			public const int absence = 2131034134;
			
			// aapt resource value: 0x7f050013
			public const int exitButton = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int help_button = 2131034132;
			
			// aapt resource value: 0x7f050012
			public const int loginButton = 2131034130;
			
			// aapt resource value: 0x7f050009
			public const int login_title = 2131034121;
			
			// aapt resource value: 0x7f05000e
			public const int password = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int passwordText = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int passwordchangeBio = 2131034123;
			
			// aapt resource value: 0x7f050008
			public const int relativeLayout1 = 2131034120;
			
			// aapt resource value: 0x7f050017
			public const int settings = 2131034135;
			
			// aapt resource value: 0x7f050015
			public const int timetableBTN = 2131034133;
			
			// aapt resource value: 0x7f05000c
			public const int userName = 2131034124;
			
			// aapt resource value: 0x7f05000f
			public const int username = 2131034127;
			
			// aapt resource value: 0x7f05000a
			public const int usernameText = 2131034122;
			
			// aapt resource value: 0x7f050006
			public const int view2 = 2131034118;
			
			// aapt resource value: 0x7f050010
			public const int view3 = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int view4 = 2131034129;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Children = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ListViewTimeTable = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Login = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Menu = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int NoInternetConnection = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int NotesListViewDisplay = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Parent = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Placement = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int TimeTable = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
